<div class="contentall">
	<center>
		<img class="attention" src="<?php echo $this->base_url_public."/images/attention.png" ?>" alt="Attention" title="Attention"/> 
			<span style="color:red;font-size:0.9em">Veuillez vous <u>authentifier</u> pour accéder à cette page</span>
		<img class="attention" src="<?php echo $this->base_url_public."/images/attention.png" ?>" alt="Attention" title="Attention"/>
		<br><br>
		<input type=button class="bouton" value="Retour à l'accueil" onclick="window.location='<?php echo $this->base_url_public ?>'"/>&nbsp;&nbsp;<input type=button class="bouton" value="Se connecter" onclick="window.location='<?php echo $this->base_url_public."/auth/login/" ?>'"/>
	</center>			
</div>