<div class="contentall">
	<center>
			<span style="color:red;font-size:0.9em">
				<img class="attention" src="<?php echo $this->base_url_public."/images/attention.png" ?>" alt="Attention" title="Attention"/>
				Vous n'avez pas les <u>droits</u> pour accéder à cette page
				<img class="attention" src="<?php echo $this->base_url_public."/images/attention.png" ?>" alt="Attention" title="Attention"/>
				<br>
				<img class="attention" src="<?php echo $this->base_url_public."/images/attention.png" ?>" alt="Attention" title="Attention"/>
				Veuillez vous déconnecter et vous reconnecter avec un autre compte.
				<img class="attention" src="<?php echo $this->base_url_public."/images/attention.png" ?>" alt="Attention" title="Attention"/>
			</span>
		<br><br>
		<input type=button class="bouton" value="Retour à l'accueil" onclick="window.location='<?php echo $this->base_url_public ?>'"/>&nbsp;&nbsp;<input type=button class="bouton" value="Déconnexion" onclick="window.location='<?php echo $this->base_url_public ?>/auth/logout/'"/>
	</center>
</div>