
   
	
		<form name="modifier" action="<?php echo $this->url('admin',['action'=>'insertmatricestd']);?>" method="post">
		<?php 
			$tabDuree = array('T0'=>'T0','T0_1H'=>'T0 + 1H','T0_2H'=>'T0 + 2H','T0_4H'=>'T0 + 4H','T0_8H'=>'T0 + 8H','T0_12H'=>'T0 + 12H','T0_24H'=>'T0 + 24H');
			$tabEtat = array('DEG_10'=>'90%','DEG_30'=>'70%','DEG_50'=>'50%','DEG_80'=>'20%','HS'=>'0%');
			echo '<table>
					<tr>
					<td></td>';
			foreach($tabEtat as $k=>$v)
			{
				echo '<td>'.$v.'</td>';
			}
			echo '</tr>';
			foreach($this->categorie as $categorie)
			{
			    
				echo '<tr><td><td colspan=5 align="center">'.$categorie->typo_categorie.'</td><td>Pas</td><td><input type name="Pas_'.$categorie->id_typo.'" onchange="calcPasIG(this)"/></td></tr>';
				foreach($tabDuree as $k1=>$v1)
				{
					echo '<tr><td>'.$v1.'</td>';
					foreach($tabEtat as $k2=>$v2)
					{    
						$v = $this->ponderation->current();
						$v = $v->getArrayCopy();
						if(!isset($v['ponderation']))
						    $ponderation = 0;
						else
						    $ponderation = $v['ponderation'];
						    
						$onblur = '';
						if($k1=='T0') $onblur = 'onblur="calcPasIG(document.getElementsByName(\'Pas_'.$categorie->id_typo.'\').item(0))"';
						echo '<td><input type="number" '.$onblur.' name="'.$categorie->id_typo.'@'.$k1.'@'.$k2.'" id="'.$categorie->id_typo.'@'.$k1.'@'.$k2.'" value="'.$ponderation.'" step="0.1" min="0" max="10"></td>';
					    
						$this->ponderation->next();
					}
					echo '</tr>';
				}
			}
			echo '</table>';
			echo '<input type="submit" name="Enregistrer" value="Enregistrer" />';
		?>
		</form>
	
