<?php
$this->headTitle('Roles');

/*$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Roles'=>$this->url('roles'),
            ]);
*/
?>


<p>
<a class="btn btn-default" href="
    <?= $this->url('roles', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ajout d'un Role
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Nom</th>
        <th>Description</th>
        <th>Date Création</th>
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($roles as $role): ?>
    
    <tr>
        <td><?= $this->escapeHtml($role->getId()); ?></td>
        <td>
            <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                <?= $this->escapeHtml($role->getName()); ?>
            </a> 
        </td>
        <td><?= utf8_decode($this->escapeHtml($role->getDescription())); ?></a> 
        </td>
        <td><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>        
        <td>
            <?php if ($role->getName() != 'Super-administrateur'): ?>
            </nobr>
            <a class="btn btn-info" href="<?= $this->url('roles', 
                    ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Modifier
            </a> 
            |
             <a class="btn btn-danger" href="<?= $this->url('roles',
                    ['action'=>'delete', 'id'=>$role->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Supprimer
            </a>
            </nobr>
            <?php endif; ?>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>




