
            <td><font face='verdana' size='1'><?=$counter ?></font></td>
            <td><font face='verdana' size='1'><?=$id_ticket ?></font></td>
            <td><font face='verdana' size='1'><?=$categorie_service?></font></td>
            <td><font face='verdana' size='1'><?=$typo_service?></font></td>
            <td><font face='verdana' size='1'><font face='verdana' size='1'><?=$sous_systeme?></font></td>
            <td><font face='verdana' size='1'><?=$IG?></font></td>
            <td><font face='verdana' size='1'><?=$IG_fin?></font></td>
            <td><font face='verdana' size='1'><?=$duree_incident?></font></td>
            <td><font face='verdana' size='1'><?=$debut_incident?></font></td>";
            <?php if ($cloture == 'OUI'): ?>
            	<td bgcolor='#A2B5CD'><font face='verdana' size='1'><?=$date_cloture_incident?></font></td>
            <?php else: ?>
            	<td><font face='verdana' size='1'><?=$date_cloture_incident?></font></td>
            <?php endif; ?>

            <td><font face='verdana' size='1'><?=$date_objectifDES?></font></td>
            <td><font face='verdana' size='1'><?=$GTR?></font></td>
            <td><font face='verdana' size='1'><?=$deb_month_inc?></font></td>
            <td><font face='verdana' size='1'><?=$deb_week_inc?></font></td>
            <td><font face='verdana' size='1'><?=$deb_day_inc?></font></td>
            <td><font face='verdana' size='1'><?=$debJ04?></font></td>
            <td><font face='verdana' size='1'><?=$debH918?></font></td>
            <td><font face='verdana' size='1'><?=$fin_month_inc?></font></td>
            <td><font face='verdana' size='1'><?=$fin_week_inc?></font></td>
            <td><font face='verdana' size='1'><?=$fin_day_inc?></font></td>
            <td><font face='verdana' size='1'><?=$finJ04?></font></td>
            <td><font face='verdana' size='1'><?=$finH918?></font></td>
            <td><font face='verdana' size='1'><?=$gtrM12?></font></td>
            <td><font face='verdana' size='1'><?=$gtrM8?></font></td>
            <td><font face='verdana' size='1'><?=$gtrM4?></font></td>
            <td><font face='verdana' size='1'><?=$nom_admin?></font></td>";
            </tr>