<font face='verdana' size='3'><b>Dashboard IG du <font color='#000080'><?=$dateFirstDay ?></font>  au  <font color='#000080'><?= $dateLastDay ?> </font></b></font>
<table class="migStyle" border='1' width='97%' bordercolor='gray' cellpadding='1' cellspacing='0'>
    	  <tr><th width='auto'><b>#</b></th>
    	  <th width='auto'><font face='verdana' size='1'><b>No. Ticket</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Catégorie de Service</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>APP / Service</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Sous-Système en défaut</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>IG de départ</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>IG de fin</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Durée impact</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Début de l'incident</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Date de clôture</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Objectif DESIF</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Temps avant GTR</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Date_DEB-mois[1-12]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Date_DEB-semaine[1-52]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Date_DEB-jour[1-7]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>DEB-J[L-D]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>DEB-H[9h-18h]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Date_FIN-mois[1-12]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Date_FIN-semaine[1-52]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Date_FIN-jour[1-7]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>FIN-J[L-D]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>FIN-H[9h-18h]</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>GTR<12h</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>GTR<8h</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>GTR<4h</b></font></th>
    	  <th width='auto'><font face='verdana' size='1'><b>Pilote incident</b></font></th></tr>